SELECT
	*
FROM
	(
		SELECT
			NCT_ID,
			TO_DATE(VERIFICATION_MONTH_YEAR, 'Month YYYY') AS VERIFICATION_DATE,
			TO_DATE(COMPLETION_MONTH_YEAR, 'Month YYYY') AS COMPLETION_DATE,
			TO_DATE(PRIMARY_COMPLETION_MONTH_YEAR, 'Month YYYY') AS PRIMARY_COMPLETION_DATE,
			STUDY_TYPE,
			OVERALL_STATUS,
			PHASE,
			ENROLLMENT
		FROM
			PUBLIC.STUDIES
	) AS UNCOMPUTED
WHERE
	(
		-- NCT_ID IN ('NCT00000120', 'NCT00000125')AND
		OVERALL_STATUS != 'Withdrawn'
		AND (
			PRIMARY_COMPLETION_DATE >= '2008-01-01'::DATE
			OR (
				PRIMARY_COMPLETION_DATE IS NULL
				AND (
					COMPLETION_DATE >= '2008-01-01'::DATE
					OR COMPLETION_DATE IS NULL
				)
			)
		)
		AND STUDY_TYPE = 'Interventional'
		AND (
			PHASE != 'Phase 1'
			OR PHASE != 'Early Phase 1'
		)
		AND (
			OVERALL_STATUS = 'Terminated'
			OR OVERALL_STATUS = 'Completed'
)
		AND (
					PRIMARY_COMPLETION_DATE < '2012-09-01'::DATE
					OR PRIMARY_COMPLETION_DATE IS NULL
			)
		AND (
					-- COMPLETION_DATE IS NULL
					PRIMARY_COMPLETION_DATE IS NULL
					AND VERIFICATION_DATE < '2012-09-01'::DATE
					AND VERIFICATION_DATE > '2008-01-01'::DATE
				)
	)
ORDER BY
	NCT_ID