SELECT
	NCT_ID,
	STUDY_FIRST_SUBMITTED_DATE,
	STUDY_FIRST_POSTED_DATE_TYPE,
	VERIFICATION_DATE,
	COMPLETION_DATE,
	PRIMARY_COMPLETION_MONTH_YEAR,
	PRIMARY_COMPLETION_DATE_TYPE,
	PRIMARY_COMPLETION_DATE,
	STUDY_TYPE,
	OVERALL_STATUS,
	PHASE,
	ENROLLMENT
FROM
	CTGOV.STUDIES
WHERE
	(
		NCT_ID IN ('NCT00000120', 'NCT00000125')
		AND
		overall_status != 'Withdrawn'
		-- AND
		-- 	-- STUDY_FIRST_SUBMITTED_DATE < '2013-09-27'::DATE
		-- (
		-- 	PRIMARY_COMPLETION_DATE >= '2008-01-01'::DATE
		-- 	OR (
		-- 		PRIMARY_COMPLETION_DATE IS NULL
		-- 		AND (
		-- 			COMPLETION_DATE >= '2008-01-01'::DATE
		-- 			OR COMPLETION_DATE IS NULL
		-- 		)
		-- 	)
		-- )
		-- AND STUDY_TYPE = 'Interventional'
		-- AND (
		-- 	PHASE != 'Phase 1'
		-- 	OR PHASE != 'Early Phase 1'
		-- )
		-- AND (
		-- 	OVERALL_STATUS = 'Terminated'
		-- 	OR OVERALL_STATUS = 'Completed'
		-- )
		-- 	AND (
		-- 			PRIMARY_COMPLETION_DATE < '2012-09-01'::DATE
		-- 			OR PRIMARY_COMPLETION_DATE IS NULL
		-- 		)
		-- 	AND (
		-- 			-- COMPLETION_DATE IS NULL
		-- 			PRIMARY_COMPLETION_DATE IS NULL
		-- 			AND VERIFICATION_DATE < '2012-09-01'::DATE
		-- 			AND VERIFICATION_DATE > '2008-01-01'::DATE
		-- 		)
	)
ORDER BY
	NCT_ID