# Environment variables:
#
# DOCKER_POSTGRES_DATA_DIR : directory for persistence of Postgres data
#
# PGPORT                   : Postgres port
# PGPASSWORD               : Postgres password
services:
  db-pg:
    image: clinicaltrials-aact-db:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./data/aact/db-dump:/aact-data
      - ${DOCKER_POSTGRES_DATA_DIR}:/var/lib/postgresql/data
      - ./script:/script
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:-password}
    ports:
      - "${PGPORT:-5432}:5432"
