stages:
  download-20170105:
    cmd: stages/01_download_db_20170105.sh
    deps:
      - stages/01_download_db_20170105.sh
    outs:
      - download/aact/db-dump/20170105_clinical_trials.zip
  download-20240430:
    cmd: stages/01_download_db_20240430.sh
    deps:
      - stages/01_download_db_20240430.sh
    outs:
      - download/aact/db-dump/20240430_clinical_trials.zip
  download-paper-data:
    cmd: stages/01_download_paper_data.sh
    deps:
      - stages/01_download_paper_data.sh
    outs:
      - download/anderson2015
  build-paper-data:
    cmd: stages/02_build-anderson2015.sh
    deps:
      - stages/02_build-anderson2015.sh
      - data/anderson2015
    outs:
      - brick/anderson2015
