params:
  - 'params.yaml'
stages:
  download-20170105:
    cmd: stages/01_download_db_20170105.sh
    deps:
      - stages/01_download_db_20170105.sh
    outs:
      - download/aact/db-dump/20170105_clinical_trials.zip
  download-20240430:
    cmd: stages/01_download_db_20240430.sh
    deps:
      - stages/01_download_db_20240430.sh
    outs:
      - download/aact/db-dump/20240430_clinical_trials.zip
  download-paper-data:
    cmd: stages/01_download_paper_data.sh
    deps:
      - stages/01_download_paper_data.sh
    outs:
      - download/anderson2015
  build-paper-data:
    cmd: stages/02_build-anderson2015.sh
    deps:
      - stages/02_build-anderson2015.sh
      - stages/csv2parquet.py
      - download/anderson2015
    outs:
      - brick/anderson2015
  #download-ctgov-data:
  #  outs:
  #    - brick/ctgov/historical
  #  deps:
  #    - stages/01_download_cts.R
  #    - download/aact/db-dump/20240430_clinical_trials.zip
  #  cmd: make docker-compose-up; Rscript stages/01_download_cts.R
  download-cthist-json:
    cmd: stages/01_download_cthist_json.sh
    deps:
      - stages/01_download_cthist_json.sh
      - stages/fetch-cthist-json.pl
      - brick/anderson2015
      - download/aact/db-dump/20240430_clinical_trials.zip
    outs:
      - download/ctgov/historical:
          # Allow the stage to avoid downloading unchanged files
          persist: true
  build-ctgov-historical-records:
    cmd:
      - mkdir -p brick/ctgov/historical
      - duckdb < sql/create_cthist_preproc.sql
    deps:
      - sql/create_cthist_preproc.sql
      - download/ctgov/historical
    outs:
      - brick/ctgov/historical/records.parquet
  build-ctgov-studies-all:
    foreach: ${param}
    do:
      cmd:
        - mkdir -p $(dirname ${item.output.all})
        - |
          . .env;
          (
            if [ -n "$MY_DUCKDB_TEMP_DIR" ] && [ -d "$MY_DUCKDB_TEMP_DIR" ]; then
              echo "Setting the DuckDB temp_directory to $MY_DUCKDB_TEMP_DIR" >&2 ;
              echo "SET temp_directory='$MY_DUCKDB_TEMP_DIR';" ;
            fi;
            if [ -n "$MY_DUCKDB_MEMORY_LIMIT" ]; then
              echo "Setting the DuckDB memory_limit to $MY_DUCKDB_MEMORY_LIMIT" >&2 ;
              echo "SET memory_limit = '$MY_DUCKDB_MEMORY_LIMIT';" ;
            fi;
            script/tt-render-by-param ${key} sql/create_cthist_all.sql
          ) | duckdb
      deps:
        - sql/create_cthist_all.sql
        - brick/ctgov/historical/records.parquet
      outs:
        - ${item.output.all}
  build-ctgov-studies-hlact-filtered:
    foreach: ${param}
    do:
      cmd:
        - make docker-compose-up
        - mkdir -p $(dirname ${item.output.hlact-filtered}) brick/flowchart-counts
        - . .env; script/tt-render-by-param ${key} sql/create_cthist_hlact.sql | duckdb
        - . .env; script/cthist_hlact_flowchart_partial_sql.sh ${key} > brick/flowchart-counts/${key}.csv
      deps:
        - sql/create_cthist_hlact.sql
        - ${item.output.all}
        - download/aact/db-dump/20240430_clinical_trials.zip
        - sql/params/hlact-filter
      outs:
        - ${item.output.hlact-filtered}
        - brick/flowchart-counts/${key}.csv
  #analysis-driver-sliding_sliding-window:
  #  cmd: |
  #    Rscript analysis/driver-sliding.R params.yaml sliding-window
  #  deps:
  #    - brick/sliding-window
  #    - params.yaml
  #    - analysis/driver-sliding.R
  #  outs:
  #    - figtab/sliding-window
  analysis-driver-sliding_long-observe:
    cmd: |
      Rscript analysis/driver-sliding.R params.yaml long-observe
    deps:
      - brick/long-observe
      - params.yaml
      - analysis/driver-sliding.R
    outs:
      - figtab/long-observe
  analysis-driver-sliding_yearly_obs36:
    cmd: |
      Rscript analysis/driver-sliding.R params.yaml yearly_obs36
    deps:
      - brick/yearly_obs36
      - params.yaml
      - analysis/driver-sliding.R
    outs:
      - figtab/yearly_obs36
  analysis-driver-anderson2015-compare-stacked:
    cmd: |
      Rscript analysis/driver-anderson2015-compare-stacked.R
    deps:
      - brick/anderson2015
      - brick/analysis-20130927
      - params.yaml
      - analysis/driver-anderson2015-compare-stacked.R
    outs:
      - figtab/anderson2015.original
      - figtab/anderson2015.new
  analysis-driver-rule-effective-date:
    cmd: |
      Rscript analysis/driver-rule-effective-date.R
    deps:
      - brick/rule-effective-date-before
      - brick/rule-effective-date-after
      - params.yaml
      - analysis/driver-rule-effective-date.R
    outs:
      - figtab/rule-effective
