params:
  - 'params.yaml'
stages:
  download-20170105:
    cmd: stages/01_download_db_20170105.sh
    deps:
      - stages/01_download_db_20170105.sh
    outs:
      - download/aact/db-dump/20170105_clinical_trials.zip
  download-20240430:
    cmd: stages/01_download_db_20240430.sh
    deps:
      - stages/01_download_db_20240430.sh
    outs:
      - download/aact/db-dump/20240430_clinical_trials.zip
  download-paper-data:
    cmd: stages/01_download_paper_data.sh
    deps:
      - stages/01_download_paper_data.sh
    outs:
      - download/anderson2015
  build-paper-data:
    cmd: stages/02_build-anderson2015.sh
    deps:
      - stages/02_build-anderson2015.sh
      - stages/csv2parquet.py
      - download/anderson2015
    outs:
      - brick/anderson2015
  #download-ctgov-data:
  #  outs:
  #    - brick/ctgov/historical
  #  deps:
  #    - stages/01_download_cts.R
  #    - download/aact/db-dump/20240430_clinical_trials.zip
  #  cmd: make docker-compose-up; Rscript stages/01_download_cts.R
  download-cthist-json:
    cmd: stages/01_download_cthist_json.sh
    deps:
      - stages/01_download_cthist_json.sh
      - stages/fetch-cthist-json.pl
      - brick/anderson2015
      - download/aact/db-dump/20240430_clinical_trials.zip
    outs:
      - download/ctgov/historical:
          # Allow the stage to avoid downloading unchanged files
          persist: true
  build-ctgov-studies-all:
    foreach: ${param}
    do:
      cmd:
        - mkdir -p $(dirname ${item.output.all})
        - script/tt-render-by-param ${key} sql/create_cthist_all.sql | duckdb
      deps:
        - sql/create_cthist_all.sql
        - download/ctgov/historical
      outs:
        - ${item.output.all}
  build-ctgov-studies-hlact-filtered:
    foreach: ${param}
    do:
      cmd:
        - make docker-compose-up
        - mkdir -p $(dirname ${item.output.hlact-filtered})
        - . .env; script/tt-render-by-param ${key} sql/create_cthist_hlact.sql | duckdb
      deps:
        - sql/create_cthist_hlact.sql
        - ${item.output.all}
        - download/aact/db-dump/20240430_clinical_trials.zip
      outs:
        - ${item.output.hlact-filtered}
  #analysis-driver-sliding_sliding-window:
  #  cmd: |
  #    Rscript analysis/driver-sliding.R params.yaml sliding-window
  #  deps:
  #    - brick/sliding-window
  #    - params.yaml
  #    - analysis/driver-sliding.R
  #  outs:
  #    - figtab/sliding-window
  analysis-driver-sliding_long-observe:
    cmd: |
      Rscript analysis/driver-sliding.R params.yaml long-observe
    deps:
      - brick/long-observe
      - params.yaml
      - analysis/driver-sliding.R
    outs:
      - figtab/long-observe
