params:
  - 'params.yaml'
stages:
  download-20170105:
    cmd: stages/01_download_db_20170105.sh
    deps:
      - stages/01_download_db_20170105.sh
    outs:
      - download/aact/db-dump/20170105_clinical_trials.zip
  download-20240430:
    cmd: stages/01_download_db_20240430.sh
    deps:
      - stages/01_download_db_20240430.sh
    outs:
      - download/aact/db-dump/20240430_clinical_trials.zip
  download-paper-data:
    cmd: stages/01_download_paper_data.sh
    deps:
      - stages/01_download_paper_data.sh
    outs:
      - download/anderson2015
  build-paper-data:
    cmd: stages/02_build-anderson2015.sh
    deps:
      - stages/02_build-anderson2015.sh
      - stages/csv2parquet.py
      - download/anderson2015
    outs:
      - brick/anderson2015
  #download-ctgov-data:
  #  outs:
  #    - brick/ctgov/historical
  #  deps:
  #    - stages/01_download_cts.R
  #    - download/aact/db-dump/20240430_clinical_trials.zip
  #  cmd: make docker-compose-up; Rscript stages/01_download_cts.R
  download-cthist-json:
    cmd: stages/01_download_cthist_json.sh
    deps:
      - stages/01_download_cthist_json.sh
      - stages/fetch-cthist-json.pl
      - brick/anderson2015
      - download/aact/db-dump/20240430_clinical_trials.zip
    outs:
      - download/ctgov/historical:
          # Allow the stage to avoid downloading unchanged files
          persist: true
  build-ctgov-historical-records:
    cmd:
      - mkdir -p brick/ctgov/historical
      - duckdb < sql/create_cthist_preproc.sql
    deps:
      - sql/create_cthist_preproc.sql
      - download/ctgov/historical
    outs:
      - brick/ctgov/historical/records.parquet
  build-ctgov-studies-all:
    foreach: ${param}
    do:
      cmd:
        - mkdir -p $(dirname ${item.output.all})
        - |
          . .env;
          (
            if [ -n "$MY_DUCKDB_TEMP_DIR" ] && [ -d "$MY_DUCKDB_TEMP_DIR" ]; then
              echo "Setting the DuckDB temp_directory to $MY_DUCKDB_TEMP_DIR" >&2 ;
              echo "SET temp_directory='$MY_DUCKDB_TEMP_DIR';" ;
            fi;
            if [ -n "$MY_DUCKDB_MEMORY_LIMIT" ]; then
              echo "Setting the DuckDB memory_limit to $MY_DUCKDB_MEMORY_LIMIT" >&2 ;
              echo "SET memory_limit = '$MY_DUCKDB_MEMORY_LIMIT';" ;
            fi;
            script/tt-render-by-param ${key} sql/create_cthist_all.sql
          ) | duckdb
      deps:
        - sql/create_cthist_all.sql
        - brick/ctgov/historical/records.parquet
      outs:
        - ${item.output.all}
  build-ctgov-studies-hlact-filtered:
    foreach: ${param}
    do:
      cmd:
        - make docker-compose-up
        - mkdir -p $(dirname ${item.output.hlact-filtered}) brick/flowchart-counts
        - . .env; script/tt-render-by-param ${key} sql/create_cthist_hlact.sql | duckdb
        - . .env; script/cthist_hlact_flowchart_partial_sql.sh ${key} > brick/flowchart-counts/${key}.csv
      deps:
        - sql/create_cthist_hlact.sql
        - ${item.output.all}
        - download/aact/db-dump/20240430_clinical_trials.zip
        - sql/params/hlact-filter
        - script/cthist_hlact_flowchart_partial_sql.sh
      outs:
        - ${item.output.hlact-filtered}
        - brick/flowchart-counts/${key}.csv
  process-driver-sliding:
    foreach:
      #- sliding-window
      - long-observe
      - yearly_obs36
    do:
      cmd:
        Rscript analysis/driver-sliding-process.R params.yaml ${item}
      deps:
        - brick/${item}
        - params.yaml
        - analysis/driver-sliding-process.R
      outs:
        - brick/${item}_processed
  analysis-driver-sliding:
    foreach:
      #- sliding-window
      - long-observe
      - yearly_obs36
    do:
      cmd: |
        Rscript analysis/driver-sliding.R params.yaml ${item}
      deps:
        - brick/${item}_processed
        - params.yaml
        - analysis/driver-sliding.R
      outs:
        - figtab/${item}
  analysis-driver-anderson2015-survival:
    cmd: |
      Rscript analysis/driver-anderson2015-survival.R
    deps:
      - brick/anderson2015
      - analysis/driver-anderson2015-survival.R
    outs:
      - figtab/anderson2015
  analysis-driver-anderson2015-compare-stacked:
    cmd: |
      Rscript analysis/driver-anderson2015-compare-stacked.R
    deps:
      - brick/anderson2015
      - brick/analysis-20130927
      - params.yaml
      - analysis/driver-anderson2015-compare-stacked.R
    outs:
      - figtab/anderson2015.original
      - figtab/anderson2015.new
  process-driver-rule-effective-date:
    cmd: |
      Rscript analysis/driver-rule-effective-date-process.R
    deps:
      - brick/rule-effective-date-before
      - brick/rule-effective-date-after
      - params.yaml
      - analysis/driver-rule-effective-date-process.R
    outs:
      - brick/rule-effective-date_processed
  analysis-driver-rule-effective-date:
    cmd: |
      Rscript analysis/driver-rule-effective-date.R
    deps:
      - brick/rule-effective-date_processed
      - params.yaml
      - analysis/driver-rule-effective-date.R
    outs:
      - figtab/rule-effective
  analysis-driver-rule-effective-date-extra-analysis:
    cmd: |
      Rscript analysis/driver-rule-effective-date-extra-analysis.R
    deps:
      - brick/rule-effective-date_processed
      - params.yaml
      - analysis/driver-rule-effective-date-extra-analysis.R
    outs:
      - figtab/rule-effective-extra-analysis
  plotter_py:
    cmd: |
      python3 analysis/plotter.py
    deps:
      - analysis/plotter.py
      - analysis/utils.py
      - brick/rule-effective-date_processed
      - brick/yearly_obs36_processed
    outs:
      - figtab/plotter_py
  aggregate-data:
    cmd: |
      Rscript analysis/driver-aggregate-data.R
    deps:
      - analysis/driver-aggregate-data.R
      - brick/rule-effective-date_processed
      - brick/yearly_obs36_processed
    outs:
      - figtab/aggregate-data
  process-post-rule-to-20240430:
    cmd: |
      Rscript analysis/driver-post-rule-to-20240430-process.R
    deps:
      - analysis/driver-post-rule-to-20240430-process.R
      - params.yaml
      - brick/post-rule-to-20240430
    outs:
      - brick/post-rule-to-20240430_processed
  analysis-post-rule-to-20240430-by_sponsor:
    cmd: |
      Rscript analysis/driver-results-compliance-by-sponsor.R
    deps:
      - analysis/driver-results-compliance-by-sponsor.R
      - brick/post-rule-to-20240430_processed
    outs:
      - brick/post-rule-to-20240430-by_sponsor
